spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/main
    username: postgres
    password: senha01

  sql:
    init:
      mode: always

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true